### ISSUE TITLE
Returning multiple turboStreams

### ISSUE THREAD

**Issue by zewa666** [deriegle/express-hotwire#42]
- **I'm submitting a ...**
  [ ] bug report
  [ x ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Allow to return multiple turbo streams in one response

- **Other information** 
[Turbo-laravel seems to support](https://github.com/tonysm/turbo-laravel#turbo-streams-combo) such a case with a simple array form of turboStreams

**Comment by deriegle** [comment]
@zewa666 Thanks for the feature suggestion and your contributions! I've merged your change and a follow up PR to change the structure of how to send multiple turbostream responses. Check out the updated `README.md` file for the documentation.

This update has been published to npm as version `0.3.2`
