### ISSUE TITLE
Turbo Stream MIME type doesn't match Turbo Handbook

### ISSUE THREAD

**Issue by insanity54** [deriegle/express-hotwire#5]
- **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

- **Summary**
I recently updated my version of Turbo, and that caused my turbo streams to fail with an error

```
Error: Form responses must redirect to another location
    requestSucceededWithResponse turbo.es2017-esm.js:561
    receive turbo.es2017-esm.js:352
    perform turbo.es2017-esm.js:335
    start turbo.es2017-esm.js:528
    submitForm turbo.es2017-esm.js:1800
    formSubmitted turbo.es2017-esm.js:2335
    submitBubbled turbo.es2017-esm.js:1576
    submitCaptured turbo.es2017-esm.js:1566
    start turbo.es2017-esm.js:1585
    start turbo.es2017-esm.js:2246
    start turbo.es2017-esm.js:2837
    node_modules bundle.js:2932
    Webpack 4
turbo.es2017-esm.js:1846
    formSubmissionErrored turbo.es2017-esm.js:1846
    requestSucceededWithResponse turbo.es2017-esm.js:562
    receive turbo.es2017-esm.js:352
    perform turbo.es2017-esm.js:335
    start turbo.es2017-esm.js:528
    submitForm turbo.es2017-esm.js:1800
    formSubmitted turbo.es2017-esm.js:2335
    submitBubbled turbo.es2017-esm.js:1576
    (Async: EventListener.handleEvent)
    submitCaptured turbo.es2017-esm.js:1566
    (Async: EventListener.handleEvent)
    start turbo.es2017-esm.js:1585
    start turbo.es2017-esm.js:2246
    start turbo.es2017-esm.js:2837
    js turbo.es2017-esm.js:2875
    Webpack 4
```

The error message sounds like turbo is not seeing the requirement of HTTP code 303 as described in [Redirecting After a Form Submission](https://turbo.hotwire.dev/handbook/drive#redirecting-after-a-form-submission) in the Turbo handbook. This however doesn't match what I am doing which is [Streaming After a Form Submission](https://turbo.hotwire.dev/handbook/drive#streaming-after-a-form-submission). In that section, MIME type is mentioned.

I looked at the Content-Type that express-hotwire was sending, and that was `text/html; turbo-stream; charset=utf-8`. I think that might be an outdated mimetype for turbo.

https://github.com/deriegle/express-hotwire/blob/6c82d13bfef1f34818f2897b67231f5de0b74463/src/lib/hotwire-middleware.ts#L138

I think that mimetype works for certain versions of Turbo. I see that mimetype in turbo-7.0.0-beta.1 but not in turbo-7.0.0-beta.7.

I think the Content-Type sent by res.turboStream should now be `text/vnd.turbo-stream.html`

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

I circumvented res.turboStream to test if this other mimetype solved the problem, and it did.

### Broken
```
                res.turboStream.append('chats', {
                    partial: 'chat/partials/chat',
                    locals: {
                        chat
                    }
                })
```

### Working
```
                res.set('Content-Type', 'text/vnd.turbo-stream.html');
                res.render('chat/partials/chat', { chat });
```

Of course this is a workaround just to see if I had correctly identified the problem. I appreciate this library so I forked and came up with a patch. I'm not sure if it's right, because the older mimetype has 'utf-8' in there and I don't know if that's supposed to be in there on the new one. It definitely works without the utf-8, though.

Also I'm unsure about `git cz` mentioned in the Contributing guidelines. is that supposed to be `git commit -cz`? And is that only needed if a git commit was created without a message?

Ohh... It's an actual program! https://github.com/commitizen/cz-cli

I'm going to have to take some time to learn cz but for now here's a personal fork which implements the updated mimetype and solved the issue I was seeing.

https://github.com/deriegle/express-hotwire/compare/main...insanity54:main#diff-b7ad7cfc2914bb92aa8b9e7c0892dcc53e9900e7940a31e77b0518118ee92860

**Comment by deriegle** [comment]
@insanity54 Thank you so much for such a detailed issue description and for forking the repository and adding your fix. I didn't notice this issue until now, but I have resolved this issue in the new version `0.3.1` of this package.

[express-hotwire@0.3.1](https://www.npmjs.com/package/express-hotwire)
